2017-10-19 15:23:14,993 - TdmApplication - DEBUG - DddDb().__init__(name='ddds', default_ddds=[u'recipehelp'])
2017-10-19 15:23:14,993 - TdmApplication - DEBUG - DddDb(): DB file name is '/home/gusmatssar/recipedialogue/tdm/ddds.json'
2017-10-19 15:23:15,004 - TdmApplication - DEBUG - FrontendConnectionHandler(id=139734493784464, session=None).open()
2017-10-19 15:23:15,005 - TdmApplication - DEBUG - thread_manager.create_thread() with threading.active_count()=3
2017-10-19 15:23:15,006 - TdmApplication - DEBUG - FrontendConnectionHandler(id=139734493784464, session=None).on_message({"handshake_content": {"session_id": null, "keep_session_alive": false}, "name": "Frontend"})
2017-10-19 15:23:15,007 - TdmApplication - DEBUG - FrontendConnectionHandler(id=139734493784464, session=None)._register({"handshake_content": {"session_id": null, "keep_session_alive": false}, "name": "Frontend"})
2017-10-19 15:23:15,008 - TdmApplication - DEBUG - thread_manager.create_thread() with threading.active_count()=4
2017-10-19 15:23:15,009 - TdmApplication - DEBUG - Creating backend and session with id 2017-10-19T15_23_14_0.
2017-10-19 15:23:15,134 - TdmApplication - ERROR - Error trying to receive message u'{"handshake_content": {"session_id": null, "keep_session_alive": false}, "name": "Frontend"}'.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tdm/maharani/session_management/frontend_connection_handler.py", line 36, in on_message
    self._handle_message(message)
  File "/usr/lib64/python2.7/site-packages/tdm/maharani/session_management/frontend_connection_handler.py", line 46, in _handle_message
    self._register(message)
  File "/usr/lib64/python2.7/site-packages/tdm/maharani/session_management/frontend_connection_handler.py", line 74, in _register
    self._backend.initialize()
  File "/usr/lib64/python2.7/site-packages/tdm/backend.py", line 407, in initialize
    self._backend.initialize()
  File "/usr/lib64/python2.7/site-packages/tdm/backend.py", line 245, in initialize
    self.add_ddds(self._ddds, [self.language_code])
  File "/usr/lib64/python2.7/site-packages/tdm/backend.py", line 271, in add_ddds
    ddd_names, languages=languages, logger=self.logger, use_word_list_correction=use_word_list_correction)
  File "/usr/lib64/python2.7/site-packages/tdm/ddd_set_loader.py", line 12, in ddds_as_list
    ddds_dict = self._load_ddds(ddds, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tdm/ddd_set_loader.py", line 24, in _load_ddds
    ddds[ddd_name] = self._load_ddd(ddd_name, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tdm/ddd_set_loader.py", line 30, in _load_ddd
    return ddd_loader.load(only_py_domain)
  File "/usr/lib64/python2.7/site-packages/tdm/ddd_loader.py", line 49, in load
    device_class = self._load_py_module_class(device_module, DddDevice)
  File "/usr/lib64/python2.7/site-packages/tdm/ddd_loader.py", line 151, in _load_py_module_class
    module = self._load_py_module(module_path)
  File "/usr/lib64/python2.7/site-packages/tdm/ddd_loader.py", line 134, in _load_py_module
    return imp.load_source(ddd_module_name, module_filename)
  File "device.py", line 4, in <module>
  File "device.py", line 5, in RecipehelpDevice
NameError: name 'DeviceWHQuery' is not defined
2017-10-19 15:23:15,136 - TdmApplication - DEBUG - FrontendConnectionHandler(id=139734493784464, session='2017-10-19T15_23_14_0').on_close()
2017-10-19 15:23:15,136 - TdmApplication - DEBUG - SessionManager.stop('2017-10-19T15_23_14_0')
2017-10-19 15:23:21,150 - TdmApplication - DEBUG - TdmApplication.stop(): Stopping HTTP server
2017-10-19 15:23:21,150 - TdmApplication - DEBUG - TdmApplication.stop(): Stopping IO-loop
2017-10-19 15:23:21,150 - TdmApplication - DEBUG - TdmApplication.stop(): Stopping sessions []
